# Generated by Django 4.0.2 on 2022-02-12 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_likes'),
        ('sosa', '0002_alter_directmessage_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
