# Generated by Django 4.0.2 on 2022-05-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_images_remove_post_image_post_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
