# Generated by Django 4.0.2 on 2022-05-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_post_images_alter_post_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='URL',
            field=models.URLField(blank=True, max_length=2500, null=True, unique=True),
        ),
    ]
