# Generated by Django 4.0.2 on 2022-05-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_alter_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='URL',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
