# Generated by Django 4.0.2 on 2022-05-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_post_images_alter_post_likes_and_more'),
        ('user', '0002_user_history_user_saved_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='history', to='post.Post'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, related_name='saved', to='post.Post'),
        ),
    ]
